version: "3"
volumes:
  disgenet_data:
services:
  disgenet_ms:
    build:
      context: .
    volumes: 
      - ./data:/data
    secrets:
      - disgenet_creds
    env_file: .env
secrets:
  disgenet_creds:
    file: ./.disgenet_creds
