version: "3.9"
services:
  disgenet_ms:
    build:
      context: .
      # args:
      #   - DEV=true
    ports:
      - "8077:8000"
    volumes: 
      - ./app:/app
      - ./data:/data
    secrets:
      - disgenet_creds
    env_file: .env
secrets:
  disgenet_creds:
    file: ./.disgenet_creds
